version: '3.9'

services:
  db:
    container_name: bd-postgres16
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres